"""empty message

Revision ID: 0329569660ad
Revises: 0d923233961c
Create Date: 2016-10-13 21:03:56.184000

"""

# revision identifiers, used by Alembic.
revision = '0329569660ad'
down_revision = '0d923233961c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.Integer(), nullable=False),
    sa.Column('content', postgresql.JSONB(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['entity_image.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('entity_image')
    ### end Alembic commands ###
