"""empty message

Revision ID: 04118d882205
Revises: b549ae010432
Create Date: 2017-02-01 15:26:56.087000

"""

# revision identifiers, used by Alembic.
revision = '04118d882205'
down_revision = 'b549ae010432'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matching_id', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_matching_id_parent_id'), 'matching_id', ['parent_id'], unique=False)
    op.create_foreign_key(None, 'matching_id', 'matching_id', ['parent_id'], ['id'], ondelete='CASCADE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matching_id', type_='foreignkey')
    op.drop_index(op.f('ix_matching_id_parent_id'), table_name='matching_id')
    op.drop_column('matching_id', 'parent_id')
    ### end Alembic commands ###
