"""empty message

Revision ID: 0d923233961c
Revises: cfade2aa00e2
Create Date: 2016-10-12 15:51:14.934000

"""

# revision identifiers, used by Alembic.
revision = '0d923233961c'
down_revision = 'cfade2aa00e2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('schedule_time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('schedule_time_id', sa.Integer(), nullable=False),
    sa.Column('schedule_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_group_id'], ['schedule_group.id'], ),
    sa.ForeignKeyConstraint(['schedule_time_id'], ['schedule_time.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('schedule_time_id', 'schedule_group_id', name='_sch_time_sch_group_uc')
    )
    op.create_table('sch_group_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_group_id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.ForeignKeyConstraint(['schedule_group_id'], ['schedule_group.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['system.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_group_id', 'entity_id', 'system_id', name='_sch_group_entity_system_uc'),
    sa.UniqueConstraint('schedule_group_id', 'order', name='_sch_group_order_uc')
    )
    op.create_table('schedule_execute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('begin_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule_execute')
    op.drop_table('sch_group_request')
    op.drop_table('schedule')
    op.drop_table('schedule_time')
    op.drop_table('schedule_group')
    ### end Alembic commands ###
