"""empty message

Revision ID: 1cb221e6b455
Revises: 414eda9f70d0
Create Date: 2016-10-20 20:28:58.644000

"""

# revision identifiers, used by Alembic.
revision = '1cb221e6b455'
down_revision = '414eda9f70d0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'matching_id', sa.Column('remote_id', sa.String(length=80), nullable=False))
    op.create_unique_constraint('_remote_entity_id_uc', 'matching_id', ['remote_entity_id', 'remote_id'])
    op.create_index(op.f('ix_matching_id_remote_id'), 'matching_id', ['remote_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_matching_id_remote_id'), table_name='matching_id')
    op.drop_constraint('_remote_entity_id_uc', 'matching_id', type_='unique')
    op.drop_column(u'matching_id', 'remote_id')
    ### end Alembic commands ###
