"""empty message

Revision ID: 2666ad088f6b
Revises: 536f0568b77f
Create Date: 2016-10-20 16:01:17.718000

"""

# revision identifiers, used by Alembic.
revision = '2666ad088f6b'
down_revision = '536f0568b77f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'entity_image', sa.Column('external_id', sa.String(length=80), nullable=False))
    op.create_index(op.f('ix_entity_image_external_id'), 'entity_image', ['external_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_image_external_id'), table_name='entity_image')
    op.drop_column(u'entity_image', 'external_id')
    ### end Alembic commands ###
