"""empty message

Revision ID: 3586755f3f51
Revises: ff8fc61c7d46
Create Date: 2016-11-01 13:57:21.457000

"""

# revision identifiers, used by Alembic.
revision = '3586755f3f51'
down_revision = 'ff8fc61c7d46'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method_code', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id', 'method_code', name='_entity_method_name_uc'),
    sa.UniqueConstraint('method_code')
    )
    op.create_index(op.f('ix_service_method_entity_id'), 'service_method', ['entity_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_method_entity_id'), table_name='service_method')
    op.drop_table('service_method')
    ### end Alembic commands ###
