"""empty message

Revision ID: 414eda9f70d0
Revises: f088f9315be0
Create Date: 2016-10-20 20:27:23.521000

"""

# revision identifiers, used by Alembic.
revision = '414eda9f70d0'
down_revision = 'f088f9315be0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'_remote_entity_id_uc', 'matching_id', type_='unique')
    op.drop_index('ix_matching_id_remote_id', table_name='matching_id')
    op.drop_column(u'matching_id', 'remote_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'matching_id', sa.Column('remote_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_matching_id_remote_id', 'matching_id', ['remote_id'], unique=False)
    op.create_unique_constraint(u'_remote_entity_id_uc', 'matching_id', ['remote_entity_id', 'remote_id'])
    ### end Alembic commands ###
