"""empty message

Revision ID: 464fe70376fe
Revises: 3583fbeba369
Create Date: 2016-11-26 00:03:15.753000

"""

# revision identifiers, used by Alembic.
revision = '464fe70376fe'
down_revision = '3583fbeba369'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matching_id', 'local_id')
    op.add_column('matching_id', sa.Column('local_id', sa.String(length=80), nullable=False))
    op.add_column('matching_id', sa.Column('local_id_prefix', sa.String(length=80), server_default='', nullable=False))
    op.add_column('matching_id', sa.Column('remote_id_prefix', sa.String(length=80), server_default='', nullable=False))
    op.create_unique_constraint('_local_entity_local_id_loc_id_pref_remote_entity_uc', 'matching_id', ['local_entity_id', 'local_id', 'local_id_prefix', 'remote_entity_id'])
    op.create_unique_constraint('_remote_entity_remote_id_rem_id_pref_local_entity_uc', 'matching_id', ['remote_entity_id', 'remote_id', 'remote_id_prefix', 'local_entity_id'])
    op.create_index(op.f('ix_matching_id_local_id'), 'matching_id', ['local_id'], unique=False)
    op.drop_constraint(u'_remote_entity_remote_id_local_entity_uc', 'matching_id', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matching_id', 'local_id')
    op.add_column('matching_id', sa.Column('local_id', sa.Integer, nullable=False))
    op.create_index(op.f('ix_matching_id_local_id'), 'matching_id', ['local_id'], unique=False)
    op.create_unique_constraint(u'_remote_entity_remote_id_local_entity_uc', 'matching_id', ['remote_entity_id', 'remote_id', 'local_entity_id'])
    op.create_unique_constraint(u'_local_entity_local_id_remote_entity_uc', 'matching_id', ['local_entity_id', 'local_id', 'remote_entity_id'])
    op.drop_constraint('_remote_entity_remote_id_rem_id_pref_local_entity_uc', 'matching_id', type_='unique')
    op.drop_column('matching_id', 'remote_id_prefix')
    op.drop_column('matching_id', 'local_id_prefix')
    ### end Alembic commands ###
