"""empty message

Revision ID: 536f0568b77f
Revises: 0329569660ad
Create Date: 2016-10-20 15:59:54.107000

"""

# revision identifiers, used by Alembic.
revision = '536f0568b77f'
down_revision = '0329569660ad'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_api_method_entity_id'), 'api_method', ['entity_id'], unique=False)
    op.create_index(op.f('ix_api_method_operation_id'), 'api_method', ['operation_id'], unique=False)
    op.create_index(op.f('ix_api_method_protocol_id'), 'api_method', ['protocol_id'], unique=False)
    op.create_index(op.f('ix_entity_system_id'), 'entity', ['system_id'], unique=False)
    op.add_column(u'entity_image', sa.Column('root_external_id', sa.String(length=80), nullable=False))
    op.create_index(op.f('ix_entity_image_entity_id'), 'entity_image', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_image_parent_id'), 'entity_image', ['parent_id'], unique=False)
    op.drop_column(u'entity_image', 'external_id')
    op.create_index(op.f('ix_matching_id_local_entity_id'), 'matching_id', ['local_entity_id'], unique=False)
    op.create_index(op.f('ix_matching_id_remote_entity_id'), 'matching_id', ['remote_entity_id'], unique=False)
    op.create_index(op.f('ix_roles_user_id'), 'roles', ['user_id'], unique=False)
    op.create_index(op.f('ix_sch_group_request_entity_id'), 'sch_group_request', ['entity_id'], unique=False)
    op.create_index(op.f('ix_sch_group_request_schedule_group_id'), 'sch_group_request', ['schedule_group_id'], unique=False)
    op.create_index(op.f('ix_sch_group_request_system_id'), 'sch_group_request', ['system_id'], unique=False)
    op.create_index(op.f('ix_schedule_schedule_group_id'), 'schedule', ['schedule_group_id'], unique=False)
    op.create_index(op.f('ix_schedule_schedule_time_id'), 'schedule', ['schedule_time_id'], unique=False)
    op.create_index(op.f('ix_schedule_execute_schedule_id'), 'schedule_execute', ['schedule_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_execute_schedule_id'), table_name='schedule_execute')
    op.drop_index(op.f('ix_schedule_schedule_time_id'), table_name='schedule')
    op.drop_index(op.f('ix_schedule_schedule_group_id'), table_name='schedule')
    op.drop_index(op.f('ix_sch_group_request_system_id'), table_name='sch_group_request')
    op.drop_index(op.f('ix_sch_group_request_schedule_group_id'), table_name='sch_group_request')
    op.drop_index(op.f('ix_sch_group_request_entity_id'), table_name='sch_group_request')
    op.drop_index(op.f('ix_roles_user_id'), table_name='roles')
    op.drop_index(op.f('ix_matching_id_remote_entity_id'), table_name='matching_id')
    op.drop_index(op.f('ix_matching_id_local_entity_id'), table_name='matching_id')
    op.add_column(u'entity_image', sa.Column('external_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_entity_image_parent_id'), table_name='entity_image')
    op.drop_index(op.f('ix_entity_image_entity_id'), table_name='entity_image')
    op.drop_column(u'entity_image', 'root_external_id')
    op.drop_index(op.f('ix_entity_system_id'), table_name='entity')
    op.drop_index(op.f('ix_api_method_protocol_id'), table_name='api_method')
    op.drop_index(op.f('ix_api_method_operation_id'), table_name='api_method')
    op.drop_index(op.f('ix_api_method_entity_id'), table_name='api_method')
    ### end Alembic commands ###
