"""empty message

Revision ID: 7b363e1ba3dc
Revises: 6e2568473447
Create Date: 2016-12-13 11:34:51.466000

"""

# revision identifiers, used by Alembic.
revision = '7b363e1ba3dc'
down_revision = '6e2568473447'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_image', sa.Column('key', sa.String(length=80), server_default='', nullable=False))
    op.create_index(op.f('ix_entity_image_key'), 'entity_image', ['key'], unique=False)
    op.add_column('entity_image_diff', sa.Column('key', sa.String(length=80), server_default='', nullable=False))
    op.create_index(op.f('ix_entity_image_diff_key'), 'entity_image_diff', ['key'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_image_diff_key'), table_name='entity_image_diff')
    op.drop_column('entity_image_diff', 'key')
    op.drop_index(op.f('ix_entity_image_key'), table_name='entity_image')
    op.drop_column('entity_image', 'key')
    ### end Alembic commands ###
