"""empty message

Revision ID: 970aa6314176
Revises: 7dd32c220e8f
Create Date: 2016-11-08 23:47:35.851000

"""

# revision identifiers, used by Alembic.
revision = '970aa6314176'
down_revision = '7dd32c220e8f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entity_image_diff',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('root_external_id', sa.String(length=80), nullable=False),
    sa.Column('external_id', sa.String(length=80), nullable=False),
    sa.Column('content', postgresql.JSONB(), nullable=True),
    sa.Column('operation_code', sa.String(length=80), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_image_diff_entity_id'), 'entity_image_diff', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entity_image_diff_external_id'), 'entity_image_diff', ['external_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_image_diff_external_id'), table_name='entity_image_diff')
    op.drop_index(op.f('ix_entity_image_diff_entity_id'), table_name='entity_image_diff')
    op.drop_table('entity_image_diff')
    ### end Alembic commands ###
