"""empty message

Revision ID: 9bf5c4d116af
Revises: 3586755f3f51
Create Date: 2016-11-07 15:49:20.937000

"""

# revision identifiers, used by Alembic.
revision = '9bf5c4d116af'
down_revision = '3586755f3f51'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_method_operation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_method_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api_method_id'], ['api_method.id'], ),
    sa.ForeignKeyConstraint(['operation_id'], ['operation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_method_id', 'operation_id', name='_api_method_operation_uc')
    )
    op.create_index(op.f('ix_api_method_operation_api_method_id'), 'api_method_operation', ['api_method_id'], unique=False)
    op.create_index(op.f('ix_api_method_operation_operation_id'), 'api_method_operation', ['operation_id'], unique=False)
    op.create_table('api_method_url_param_entity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_method_id', sa.Integer(), nullable=False),
    sa.Column('param_name', sa.String(length=80), nullable=False),
    sa.Column('param_position', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['api_method_id'], ['api_method.id'], ),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_method_id', 'entity_id', name='_api_method_entity_id_uc'),
    sa.UniqueConstraint('api_method_id', 'param_position', name='_api_method_position_uc')
    )
    op.create_index(op.f('ix_api_method_url_param_entity_api_method_id'), 'api_method_url_param_entity', ['api_method_id'], unique=False)
    op.create_index(op.f('ix_api_method_url_param_entity_entity_id'), 'api_method_url_param_entity', ['entity_id'], unique=False)
    op.add_column(u'api_method', sa.Column('version', sa.Integer(), server_default='0', nullable=False))
    op.drop_constraint(u'_entity_operation_uc', 'api_method', type_='unique')
    op.drop_index('ix_api_method_operation_id', table_name='api_method')
    op.drop_constraint(u'api_method_operation_id_fkey', 'api_method', type_='foreignkey')
    op.drop_column(u'api_method', 'operation_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'api_method', sa.Column('operation_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'api_method_operation_id_fkey', 'api_method', 'operation', ['operation_id'], ['id'])
    op.create_index('ix_api_method_operation_id', 'api_method', ['operation_id'], unique=False)
    op.create_unique_constraint(u'_entity_operation_uc', 'api_method', ['entity_id', 'operation_id'])
    op.drop_column(u'api_method', 'version')
    op.drop_index(op.f('ix_api_method_url_param_entity_entity_id'), table_name='api_method_url_param_entity')
    op.drop_index(op.f('ix_api_method_url_param_entity_api_method_id'), table_name='api_method_url_param_entity')
    op.drop_table('api_method_url_param_entity')
    op.drop_index(op.f('ix_api_method_operation_operation_id'), table_name='api_method_operation')
    op.drop_index(op.f('ix_api_method_operation_api_method_id'), table_name='api_method_operation')
    op.drop_table('api_method_operation')
    ### end Alembic commands ###
