"""empty message

Revision ID: a1230e791a22
Revises: 7b363e1ba3dc
Create Date: 2017-01-11 19:42:28.029000

"""

# revision identifiers, used by Alembic.
revision = 'a1230e791a22'
down_revision = '7b363e1ba3dc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sch_gr_req_execute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sch_group_request_id', sa.Integer(), nullable=False),
    sa.Column('begin_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sch_group_request_id'], ['sch_group_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sch_gr_req_execute_sch_group_request_id'), 'sch_gr_req_execute', ['sch_group_request_id'], unique=False)
    op.drop_table('schedule_execute')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_execute',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('schedule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('begin_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end_datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], [u'schedule.id'], name=u'schedule_execute_schedule_id_fkey'),
    sa.PrimaryKeyConstraint('id', name=u'schedule_execute_pkey')
    )
    op.drop_index(op.f('ix_sch_gr_req_execute_sch_group_request_id'), table_name='sch_gr_req_execute')
    op.drop_table('sch_gr_req_execute')
    ### end Alembic commands ###
