"""empty message

Revision ID: b549ae010432
Revises: a1230e791a22
Create Date: 2017-01-25 16:13:41.769000

"""

# revision identifiers, used by Alembic.
revision = 'b549ae010432'
down_revision = 'a1230e791a22'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_image', sa.Column('root_entity_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_entity_image_root_entity_id'), 'entity_image', ['root_entity_id'], unique=False)
    op.create_foreign_key(None, 'entity_image', 'entity', ['root_entity_id'], ['id'])
    op.add_column('entity_image_diff', sa.Column('root_entity_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_entity_image_diff_root_entity_id'), 'entity_image_diff', ['root_entity_id'], unique=False)
    op.create_foreign_key(None, 'entity_image_diff', 'entity', ['root_entity_id'], ['id'])
    ### end Alembic commands ###

    # we build a quick link for the current connection of alembic
    connection = op.get_bind()

    connection.execute("""
        update entity_image
        set root_entity_id = entity_id
        where
        level=1 and root_entity_id is null;
        update entity_image e1
        set root_entity_id = (select e2.entity_id from entity_image e2 where e1.root_external_id=e2.external_id and e1.key=e2.key and e2.level=1)
        where
        e1.level>1 and e1.root_entity_id is null;
    """)

    op.alter_column('entity_image', 'root_entity_id', existing_type=sa.INTEGER(), nullable=False)


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entity_image_diff', type_='foreignkey')
    op.drop_index(op.f('ix_entity_image_diff_root_entity_id'), table_name='entity_image_diff')
    op.drop_column('entity_image_diff', 'root_entity_id')
    op.drop_constraint(None, 'entity_image', type_='foreignkey')
    op.drop_index(op.f('ix_entity_image_root_entity_id'), table_name='entity_image')
    op.drop_column('entity_image', 'root_entity_id')
    ### end Alembic commands ###
