"""empty message

Revision ID: d8f28476d08a
Revises: 764109dad1c8
Create Date: 2016-10-04 21:53:40.641000

"""

# revision identifiers, used by Alembic.
revision = 'd8f28476d08a'
down_revision = '764109dad1c8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_method',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_code', sa.String(length=80), nullable=False),
    sa.Column('operation_code', sa.String(length=80), nullable=False),
    sa.Column('system_code', sa.String(length=80), nullable=False),
    sa.Column('method', sa.String(length=80), nullable=False),
    sa.Column('template_url', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_code', 'operation_code', 'system_code', name='_entity_operation_system_uc')
    )
    op.create_table('matching_id',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('local_entity_code', sa.String(length=80), nullable=False),
    sa.Column('local_id', sa.Integer(), nullable=False),
    sa.Column('local_param_name', sa.String(length=80), nullable=True),
    sa.Column('remote_sys_code', sa.String(length=80), nullable=False),
    sa.Column('remote_entity_code', sa.String(length=80), nullable=False),
    sa.Column('remote_id', sa.Integer(), nullable=False),
    sa.Column('remote_param_name', sa.String(length=80), nullable=True),
    sa.CheckConstraint(u"local_param_name > '' OR remote_param_name > ''", name='_param_name_chk'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('local_entity_code', 'local_id', name='_local_entity_id_uc'),
    sa.UniqueConstraint('remote_sys_code', 'remote_entity_code', 'remote_id', name='_remote_sys_entity_id_uc')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('matching_id')
    op.drop_table('api_method')
    ### end Alembic commands ###
