"""empty message

Revision ID: f088f9315be0
Revises: 2666ad088f6b
Create Date: 2016-10-20 17:19:33.479000

"""

# revision identifiers, used by Alembic.
revision = 'f088f9315be0'
down_revision = '2666ad088f6b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'system', sa.Column('host', sa.String(length=80), nullable=False))
    op.drop_column(u'system', 'url')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'system', sa.Column('url', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.drop_column(u'system', 'host')
    ### end Alembic commands ###
