"""empty message

Revision ID: fb7944ce4a07
Revises: 1cb221e6b455
Create Date: 2016-10-26 12:56:21.167000

"""

# revision identifiers, used by Alembic.
revision = 'fb7944ce4a07'
down_revision = '1cb221e6b455'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_local_entity_id_remote_entity_uc', 'matching_id', ['local_entity_id', 'local_id', 'remote_entity_id'])
    op.drop_constraint(u'_local_entity_id_uc', 'matching_id', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'_local_entity_id_uc', 'matching_id', ['local_entity_id', 'local_id'])
    op.drop_constraint('_local_entity_id_remote_entity_uc', 'matching_id', type_='unique')
    ### end Alembic commands ###
