"""empty message

Revision ID: ff8fc61c7d46
Revises: fb7944ce4a07
Create Date: 2016-10-26 22:50:20.743000

"""

# revision identifiers, used by Alembic.
revision = 'ff8fc61c7d46'
down_revision = 'fb7944ce4a07'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_local_entity_local_id_remote_entity_uc', 'matching_id', ['local_entity_id', 'local_id', 'remote_entity_id'])
    op.create_unique_constraint('_remote_entity_remote_id_local_entity_uc', 'matching_id', ['remote_entity_id', 'remote_id', 'local_entity_id'])
    op.drop_constraint(u'_local_entity_id_remote_entity_uc', 'matching_id', type_='unique')
    op.drop_constraint(u'_remote_entity_id_uc', 'matching_id', type_='unique')
    op.add_column(u'sch_group_request', sa.Column('sampling_method', sa.String(length=80), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'sch_group_request', 'sampling_method')
    op.create_unique_constraint(u'_remote_entity_id_uc', 'matching_id', ['remote_entity_id', 'remote_id'])
    op.create_unique_constraint(u'_local_entity_id_remote_entity_uc', 'matching_id', ['local_entity_id', 'local_id', 'remote_entity_id'])
    op.drop_constraint('_remote_entity_remote_id_local_entity_uc', 'matching_id', type_='unique')
    op.drop_constraint('_local_entity_local_id_remote_entity_uc', 'matching_id', type_='unique')
    ### end Alembic commands ###
